version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-kruger
    environment:
      POSTGRES_DB: ktestfulldb
      POSTGRES_USER: ktestfull
      POSTGRES_PASSWORD: ktestpassfull
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kruger-test-network

  backend:
    build:
      context: ./backend
    container_name: kruger-back
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - URL_DATASOURCE=jdbc:postgresql://postgres:5432/ktestfulldb
      - USERNAME_DATASOURCE=ktestfull
      - PASS_DATASOURCE=ktestpassfull
      - APP_JWT_SECRET=EvaluacionTecnicaKruger1234567890
      - APP_JWT_EXPIRATION=86400000
      - URI_DEV=http://localhost:8080/ktestfull
    depends_on:
      - postgres
    volumes:
      - ./backend/src/main/resources/application.properties:/app/application.properties
    networks:
      - kruger-test-network
    
networks:
  kruger-test-network:
    driver: bridge